---
- name: Install java and nginx for backend server
  hosts: backend
  become: true
  roles:
      #- quantum_user
          - geerlingguy.java
          - geerlingguy.nginx_backend
          - mv_code_backend # use jenkins or put the .jar in the files folder
          - api_server    # setup .jar daemon aka swagger.service
          - system_server # setup .jar daemon aka quantum.service
          - monitorix

  tasks:
      - name: Set httpd_can_network_connect flag on and keep it persistent across reboots for proxy
        seboolean:
            name: httpd_can_network_connect
            state: yes
            persistent: yes
      - name: run restore context to reload selinux
        shell: restorecon -Rv /usr/share/nginx

- name: install nginx for frontend server
  hosts: frontend
  become: true
  roles:
          - geerlingguy.nginx_frontend
          - mv_code_frontend # use jenkins
          - monitorix
            #- quantum_user
  tasks:
      - name: run restore context to reload selinux
        shell: restorecon -Rv /usr/share/nginx
