---
# tasks file for java_daemon
- name: copy java_service.j2 to /etc/systemd/system/ "{{ name_of_service | default('quantum')}}"
  template:
      src: java_service.j2
      dest: "{{ systemd_service | default('/etc/systemd/system/quantum.service')}}"
      owner: root
      group: root
      mode: 0644

      #- name: reload daemon
      #  systemd:
      #      daemon_reload: yes

- name: start java.service
  systemd:
      daemon_reload: yes
      name: "{{ name_of_service | default('quantum') }}"
      state: restarted
      enabled: true
